import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faArrowUpLong,
  faArrowRightArrowLeft,
  faArrowRightLong,
  faAward,
  faBatteryFull,
  faBoltLightning,
  faBuildingColumns,
  faChartLine,
  faChevronDown,
  faCircleCheck,
  faCirclePlay,
  faClipboardCheck,
  faCloudArrowUp,
  faComments,
  faCommentsDollar,
  faDiagramProject,
  faDownload,
  faEnvelope,
  faFileCircleCheck,
  faGaugeHigh,
  faLanguage,
  faLocationDot,
  faMicrochip,
  faPaperPlane,
  faPhone,
  faShieldHalved,
  faSliders,
  faSolarPanel,
  faUsersGear,
  faUserShield,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

export type AppIcon = IconDefinition;

export const icons = {
  adminLeads: faUserShield,
  adminLocales: faLanguage,
  adminProducts: faDiagramProject,
  adminUploads: faCloudArrowUp,
  arrowRight: faArrowRightLong,
  arrowUp: faArrowUpLong,
  close: faXmark,
  award: faAward,
  battery: faBatteryFull,
  certification: faFileCircleCheck,
  check: faCircleCheck,
  chevronDown: faChevronDown,
  company: faBuildingColumns,
  consultation: faCommentsDollar,
  contactEmail: faEnvelope,
  contactLocation: faLocationDot,
  contactPhone: faPhone,
  conversion: faArrowRightArrowLeft,
  download: faDownload,
  filter: faSliders,
  growth: faChartLine,
  highTech: faMicrochip,
  location: faLocationDot,
  people: faUsersGear,
  play: faCirclePlay,
  procurement: faClipboardCheck,
  processSupport: faBoltLightning,
  quote: faComments,
  revenue: faChartLine,
  security: faShieldHalved,
  send: faPaperPlane,
  solar: faSolarPanel,
  speed: faBoltLightning,
  specs: faGaugeHigh,
} satisfies Record<string, IconDefinition>;
